[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm config set fetch-retries 5",
  "npm config set fetch-retry-mintimeout 20000",
  "npm config set fetch-retry-maxtimeout 120000",
  "rm -rf node_modules package-lock.json",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview"
